/** Type declarations for the WASM glue module generated by wasm-pack */
declare module '*.wasm' {
  const content: BufferSource;
  export default content;
}

declare module 'auths-verifier-wasm' {
  export default function init(input?: BufferSource | string): Promise<void>;
  export function verifyAttestationWithResult(attestationJson: string, issuerPkHex: string): string;
  export function verifyChainJson(attestationsJsonArray: string, rootPkHex: string): string;
}
